# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops

trigger:
- master

jobs:
- template: build-template.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-16.04'

- template: build-template.yml
  parameters:
    name: macOS
    vmImage: 'macOS-latest'

- template: build-template.yml
  parameters:
    name: Windows
    vmImage: 'vs2017-win2016'
