# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 12.x
    displayName: 'Install Node.js'
  - script: npm install
  - script: npm run compile
  - script: npm test
