apiVersion: v1
kind: Service
metadata:
  name: color-code-service
  namespace: incredible-dev
  labels:
    name: color-code
    app: color-code
spec:
  selector:
    app: color-code
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-code-deployment
  namespace: incredible-dev
  labels:
    name: color-code
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: color-code
  template:
    metadata:
      labels:
        app: color-code
    spec:
      containers:
        - name: color-code
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          env:
            - name: PORT
              value: '3000'
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: idev-secrets
                  key: COLOR_CODES_AUTH_TOKEN
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 128Mi
